boot.o: boot.S multiboot.h x86_desc.h types.h
idt-linkage.o: idt-linkage.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h x86_desc.h lib.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h idt-linkage.h keyboard.h rtc.h idt.h \
  lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h keyboard.h page.h filesystem.h
keyboard.o: keyboard.c keyboard.h types.h i8259.h lib.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h lib.h x86_desc.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h i8259.h page.h rtc.h \
  filesystem.h
